# Generated by Django 4.1.4 on 2022-12-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_detail_project_project_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_preset',
            field=models.BooleanField(default=True, verbose_name='admin-subs'),
        ),
    ]
