# Generated by Django 4.1.4 on 2022-12-24 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_subject_is_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyextension',
            name='extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.extensionservice'),
        ),
        migrations.AlterField(
            model_name='facultyextension',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
