# Generated by Django 4.1.4 on 2022-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_extensionservice_is_preset_alter_subject_is_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
