# Generated by Django 4.1.4 on 2022-12-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_announcement_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
    ]
