# Generated by Django 4.1.4 on 2022-12-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchstatus',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='head_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
