# Generated by Django 4.1.4 on 2022-12-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_extensionservice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionservice',
            name='user',
        ),
    ]
