# Generated by Django 4.1.4 on 2022-12-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_extensionservice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='detail',
            new_name='project_detail',
        ),
    ]
