# Generated by Django 4.1.4 on 2022-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_facultyextension_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionservice',
            name='is_preset',
            field=models.BooleanField(default=True, verbose_name='admin-extensions'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_preset',
            field=models.BooleanField(default=True, verbose_name='admin-subjects'),
        ),
    ]
