# Generated by Django 4.1.4 on 2022-12-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_announcement_head_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_publish',
        ),
    ]
